 export const loadCategories = (value) =>({type:'LOAD_CATEGORIES',payload:value})
 export const loadCategoryTest = (value)=>({type:'LOAD_CATEGORY_TEST',payload:value})
 export const setCurrentTest = (value)=>({type:'SET_CURRENT_TEST',payload:value})
 export const addIncorrectAnswer = (value)=>({type:'ADD_INCORRECT_ANSWER',payload:value})
 export const addCorrectAnswer = (value)=>({type:'ADD_CORRECT_ANSWER',payload:value})
 export const addAnswer = (value) => ({type:'ADD_ANSWER',payload:value})
 export const addCategory = (value) => ({type:'ADD_CATEGORY',payload:value})
 export const clearTest = () => ({type:'CLEAR_TEST'})
 export const setTimer = (value) => ({type:'SET_TIMER',payload:value})
